language: r
sudo: false
dist: trusty
cache: 
  - packages
  - ccache
latex: false

# These steps apply to all matrix jobs unless defined differently in tic.R
before_install: 
  - R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install(); remotes::install_github("tidyverse/ggplot2")'

matrix:
  fast_finish: true
  allow_failures:
    - env: NB='w/ lintr'
    - env: NB='w/ covr'
  include:
    - os: linux
      r: devel
      install: R -q -e 'tic::install()'
      after_install: R -q -e 'tic::after_install()'
      before_script: R -q -e 'tic::before_script()'
      script: R -q -e 'tic::script()'
      before_deploy: R -q -e 'tic::before_deploy()'
      deploy:
          provider: script
          script: R -q -e 'tic::deploy()'
          on:
            branch: master
            condition:
               - $TRAVIS_PULL_REQUEST = false
               - $TRAVIS_EVENT_TYPE != cron
      after_deploy: R -q -e 'tic::after_deploy()'
    - os: osx
      r: release
      install: R -q -e 'tic::install()'
      after_install: R -q -e 'tic::after_install()'
      before_script: R -q -e 'tic::before_script()'
      script: R -q -e 'tic::script()'
    - os: linux
      r: devel
      env: NB='w/ covr' 
    - os: linux
      r: devel
      env: NB='w/ lintr'

notifications:
  on_success: change # default: always
  on_failure: change # default: always
  email: false
