#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
# r_check_args: --as-cran
latex: false

# automatic deploy pkgdown docs: https://raw.githubusercontent.com/krlmlr/tic.package/master/.travis.yml
before_install: R -q -e 'install.packages("remotes"); remotes::install_github("ropenscilabs/tic"); tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'

matrix:
  include:
    - os: linux
      r: oldrel
      r_github_packages:
        - hadley/testthat
    - os: linux
      r: release
      r_github_packages:
        - hadley/testthat
    - os: linux
      r: devel
      r_github_packages:
        - hadley/testthat
    - os: osx
      r: oldrel
      r_github_packages:
        - hadley/testthat
    - os: osx
      r: release
      r_github_packages:
        - hadley/testthat
    - os: linux
      r: release
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-manual --ignore-vignettes
      r_github_packages:
        - jimhester/covr
        - hadley/testthat
      after_success:
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label
    - os: linux
      r: release
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      r_github_packages:
        - hadley/testthat
        - jimhester/lintr
      after_success:
        - Rscript -e 'library(lintr); lint_package(linters = with_defaults(commented_code_linter = NULL, closed_curly_linter = closed_curly_linter(allow_single_line = TRUE), open_curly_linter = open_curly_linter(allow_single_line = TRUE)))'
      env: NB='w/ lintr' ## Just a label


